//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestProjectMindX.serviceEnvioMasivo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="serviceEnvioMasivo.IServiceEnvioMasivoMiddleware")]
    public interface IServiceEnvioMasivoMiddleware {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEnvioMasivoMiddleware/createBeneficio", ReplyAction="http://tempuri.org/IServiceEnvioMasivoMiddleware/createBeneficioResponse")]
        string createBeneficio(MiddleWare.Servicio.CargaMasiva.BE.EBeneficio inten);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEnvioMasivoMiddleware/createBeneficio", ReplyAction="http://tempuri.org/IServiceEnvioMasivoMiddleware/createBeneficioResponse")]
        System.Threading.Tasks.Task<string> createBeneficioAsync(MiddleWare.Servicio.CargaMasiva.BE.EBeneficio inten);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceEnvioMasivoMiddlewareChannel : UnitTestProjectMindX.serviceEnvioMasivo.IServiceEnvioMasivoMiddleware, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceEnvioMasivoMiddlewareClient : System.ServiceModel.ClientBase<UnitTestProjectMindX.serviceEnvioMasivo.IServiceEnvioMasivoMiddleware>, UnitTestProjectMindX.serviceEnvioMasivo.IServiceEnvioMasivoMiddleware {
        
        public ServiceEnvioMasivoMiddlewareClient() {
        }
        
        public ServiceEnvioMasivoMiddlewareClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceEnvioMasivoMiddlewareClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceEnvioMasivoMiddlewareClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceEnvioMasivoMiddlewareClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string createBeneficio(MiddleWare.Servicio.CargaMasiva.BE.EBeneficio inten) {
            return base.Channel.createBeneficio(inten);
        }
        
        public System.Threading.Tasks.Task<string> createBeneficioAsync(MiddleWare.Servicio.CargaMasiva.BE.EBeneficio inten) {
            return base.Channel.createBeneficioAsync(inten);
        }
    }
}
